import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "locomotive-scroll/dist/locomotive-scroll.css";

import Locomotive from "@/components/Locomotive";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NITEX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <Locomotive>
          <Header />
          {children}
          <Footer />
        </Locomotive>
      </body>
    </html>
  );
}
